### PR TITLE
Nodes - Added Enum Switch node

### PR DESCRIPTION
**Pull request by diogotr7**
Maybe the name isn't the best but i'm not sure what i'd call it for it to make sense to the average user.

Acceps an enum as input, which then causes one pin per enum value to appear. The output is just whatever input corresponds to the given enum.

### CODE REVIEW

**Comment by diogotr7** [comment]
Does a user know what a "Switch" is though? I like that name but it might be a bit hard to understand.

**Comment by DarthAffe** [comment]
I'd say yes since without any technical background a switch is something to chose between different states (like on/off for power for example) and that's what is happening here - it's switching between the inputs based on a given state.
Not a native english speaker but I'd say it's the best way to describe it

**Comment by Aytackydln** [comment]
I thin that node and the Branch node is called 'Select' in Blueprints. Branch and Switch nodes return function outputs instead of 'selecting' one output

**Comment by DarthAffe** [comment]
Like i said before we are not replicating blueprints as we don't have the execution-lines. The unreal equivalent for this type of evaluation are materials and there it's like this (the Branch-node is called Switch there, which i don't really like tbh):
image

**Pull request merged**
