### PR TITLE
Introduced String Regex Condition Operator

### PR DESCRIPTION
**Pull request by F-Lehmann**
I found it useful to be able to match Strings to a Regex.

### CODE REVIEW

**Comment by F-Lehmann** [comment]
Implementation is open for discussion

**Comment by SpoinkyNL** [comment]
Hey, I like the idea. I wonder if we could add some sort of validation in the future though.
Also, the code style of these commits is vastly different from what the rest of the code uses. When I merge this I'll reformat it if you don't mind.

**Comment by F-Lehmann** [comment]
I'll look into validation tomorrow.
Feel free to reformat, I'm just used to write in that style

**Comment by SpoinkyNL** [comment]
I don't think you can do validation right now. There's no way to bind a specific input view model to an operator yet, but I was thinking that might be a useful addition

**Comment by DarthAffe** [comment]
Whats the point of this check?
```match.Value.Equals(aString);```
Isn't that preventing any match except equality of a and b (which could be tested with == too)?
If i run the regex ```My .*?-String``` against the string ```My Test-String```Evaluate returns false, but iId expect that to be true.

**Comment by DarthAffe** [comment]
Ah and btw not sure how that is handled in the other operators but if it's not ensured, that a and b are strings I'd go with something like ```string aString = (a as string) ?? a?.ToString();```

**Comment by F-Lehmann** [comment]
My intention was to have the whole sting be a single match and prevent just a substring being a match. I don't know if that's actually useful or not, just my thougts of yesterday.

Most is just copied from the other String operators. So they should have similar problems?

**Comment by F-Lehmann** [comment]
We might instead use Regex.ismatch(aString,bString) and return it's result

**Comment by DarthAffe** [comment]
Hmm not sure about the full match. It can be done with the regex, but it can't be undone. that's why I'd prefer to make it open.
Something like this would force a full match without limiting the regex:
```csharp
public override bool Evaluate(object a, object b)
{
    string regex = a?.ToString() ?? string.Empty;
    string text = b?.ToString() ?? string.Empty;

    // Ensures full match
    if(!regex.StartsWith("^")) regex = "^" + regex;
    if(!regex.EndsWith("$")) regex += "$";
         
    return Regex.IsMatch(text, regex);
}
```

**Comment by F-Lehmann** [comment]
text and regex are reversed. a: string b: regexpattern
But otherwise we might settle it that way

**Comment by SpoinkyNL** [comment]
Hmmm this brings to light an issue with how you define these operators, I think the API is not clear enough.
You can be sure it's a string because Artemis will only invoke `Evaluate` if `CompatibleTypes` matches.

While working on [data binding converters](https://github.com/Artemis-RGB/Artemis/blob/master/src/Artemis.Core/DefaultTypes/DataBindings/Converters/FloatDataBindingConverter.cs) I gained some better insights on how to handle this and I've decided to apply it to condition operators and data binding modifiers.

I'll make it so you have two options, implement a `ConditionOperator<TLeftSide, TRightSide>` or just `ConditionOperator<TLeftSide>` if you don't want to support a right-side parameter.

Then the current object-based signature of `Evaluate` can change to `Evaluate(TLeftSide a, TRightSide b)` and `Evaluate(TLeftSide a)` respectively. I think that much better signifies that the data type is always going to match what you expect and saves converting.

This has the added upside of allowing you to have a different type of right-side parameter, currently the two parameter types must always match.

The downside is you lose the flexibility of having multiple compatible types but so far [I've only used it to mark an operator to be compatible with all number types](https://github.com/Artemis-RGB/Artemis/blob/4e70e5a915a7fd229da9940d5bb83f8257271a55/src/Artemis.Core/DefaultTypes/Conditions/Operators/GreaterThanConditionOperator.cs#L8). That can be solved by restricting the parameter types to any type that is castable to `TLeftSide` and `TRightSide`.

I'll leave this PR open until I implemented this, I think it'll clean it up nicely.

**Comment by F-Lehmann** [comment]
replaced by #489

**Pull request closed without merging**
