### PR TITLE
Added Layout for Corsair ML PRO RGB Fan

### PR DESCRIPTION
**Pull request by F-Lehmann**

### CODE REVIEW

**Comment by F-Lehmann** [comment]
fixed Image size issue

**Comment by SpoinkyNL** [comment]
Good catch in the LL RGB layout name haha.
Why did you decide to make both 120mm?

I'm not against the change but just curious of the reasoning. I don't believe there is a way to tell their real physical size, but in the layout editor users may rescale them. 

So if they are 120mm by default people would have to set the scale to 1.16 for them to appear as 140mm

**Comment by F-Lehmann** [comment]
I didn't mean to include that change here, but now i begin to understand how pull requests work. This should have been my private modification, since i have 120mm Fans. I tried rescaling but that seems to be broken if one tries to enter a decimal dot. (Maybe have a look at this)

Reasoning why 120 could be the default: 

1. Scaling by 1.16666667 is much nicer to enter than 0.8571428...
2. If you don't scale them correct 140 would overlap with if you actually have 120, on the other side 120 spaced apart a little still work as expected as 140 with their led placement.

Your decision if you want to take this change.

**Comment by F-Lehmann** [comment]
Lots of new Layouts:
Gskill TridentZ RGB
ROG STRIX Z390-F
Logitech G935
Logitech G502
Logitech Powerplay

**Comment by SpoinkyNL** [comment]
Thanks! I'll merge these. I'll look into the decimal dot input issue when I get the chance

**Comment by DarthAffe** [comment]
@F-Lehmann that's because you're on a german layout, you need to enter coma instead of dot right now (due to localization).

**Comment by F-Lehmann** [comment]
That's what i thought at first glance too, but that is not the case. Neither . nor , can be entered into the scaling field

**Pull request merged**
